package persistencia;
// Generated Jan 8, 2015 9:04:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jogadores generated by hbm2java
 */
public class Jogadores  implements java.io.Serializable {


     private Long idjogador;
     private Partida partida;
     private int slot;
     private int idheroi;
     private int item1;
     private int item2;
     private int item3;
     private int item4;
     private int item5;
     private int item6;
     private int kills;
     private int mortes;
     private int assistencias;
     private int ourofinal;
     private int lasthits;
     private int denies;
     private int gpm;
     private int xpm;
     private int ourogasto;
     private int danoemtorre;
     private int hpcurado;
     private int level;
     private long idconta;
     private Set habilidadeses = new HashSet(0);

    public Jogadores() {
    }

	
    public Jogadores(Partida partida, int slot, int idheroi, int item1, int item2, int item3, int item4, int item5, int item6, int kills, int mortes, int assistencias, int ourofinal, int lasthits, int denies, int gpm, int xpm, int ourogasto, int danoemtorre, int hpcurado, int level, long idconta) {
        this.partida = partida;
        this.slot = slot;
        this.idheroi = idheroi;
        this.item1 = item1;
        this.item2 = item2;
        this.item3 = item3;
        this.item4 = item4;
        this.item5 = item5;
        this.item6 = item6;
        this.kills = kills;
        this.mortes = mortes;
        this.assistencias = assistencias;
        this.ourofinal = ourofinal;
        this.lasthits = lasthits;
        this.denies = denies;
        this.gpm = gpm;
        this.xpm = xpm;
        this.ourogasto = ourogasto;
        this.danoemtorre = danoemtorre;
        this.hpcurado = hpcurado;
        this.level = level;
        this.idconta = idconta;
    }
    public Jogadores(Partida partida, int slot, int idheroi, int item1, int item2, int item3, int item4, int item5, int item6, int kills, int mortes, int assistencias, int ourofinal, int lasthits, int denies, int gpm, int xpm, int ourogasto, int danoemtorre, int hpcurado, int level, long idconta, Set habilidadeses) {
       this.partida = partida;
       this.slot = slot;
       this.idheroi = idheroi;
       this.item1 = item1;
       this.item2 = item2;
       this.item3 = item3;
       this.item4 = item4;
       this.item5 = item5;
       this.item6 = item6;
       this.kills = kills;
       this.mortes = mortes;
       this.assistencias = assistencias;
       this.ourofinal = ourofinal;
       this.lasthits = lasthits;
       this.denies = denies;
       this.gpm = gpm;
       this.xpm = xpm;
       this.ourogasto = ourogasto;
       this.danoemtorre = danoemtorre;
       this.hpcurado = hpcurado;
       this.level = level;
       this.idconta = idconta;
       this.habilidadeses = habilidadeses;
    }
   
    public Long getIdjogador() {
        return this.idjogador;
    }
    
    public void setIdjogador(Long idjogador) {
        this.idjogador = idjogador;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public int getSlot() {
        return this.slot;
    }
    
    public void setSlot(int slot) {
        this.slot = slot;
    }
    public int getIdheroi() {
        return this.idheroi;
    }
    
    public void setIdheroi(int idheroi) {
        this.idheroi = idheroi;
    }
    public int getItem1() {
        return this.item1;
    }
    
    public void setItem1(int item1) {
        this.item1 = item1;
    }
    public int getItem2() {
        return this.item2;
    }
    
    public void setItem2(int item2) {
        this.item2 = item2;
    }
    public int getItem3() {
        return this.item3;
    }
    
    public void setItem3(int item3) {
        this.item3 = item3;
    }
    public int getItem4() {
        return this.item4;
    }
    
    public void setItem4(int item4) {
        this.item4 = item4;
    }
    public int getItem5() {
        return this.item5;
    }
    
    public void setItem5(int item5) {
        this.item5 = item5;
    }
    public int getItem6() {
        return this.item6;
    }
    
    public void setItem6(int item6) {
        this.item6 = item6;
    }
    public int getKills() {
        return this.kills;
    }
    
    public void setKills(int kills) {
        this.kills = kills;
    }
    public int getMortes() {
        return this.mortes;
    }
    
    public void setMortes(int mortes) {
        this.mortes = mortes;
    }
    public int getAssistencias() {
        return this.assistencias;
    }
    
    public void setAssistencias(int assistencias) {
        this.assistencias = assistencias;
    }
    public int getOurofinal() {
        return this.ourofinal;
    }
    
    public void setOurofinal(int ourofinal) {
        this.ourofinal = ourofinal;
    }
    public int getLasthits() {
        return this.lasthits;
    }
    
    public void setLasthits(int lasthits) {
        this.lasthits = lasthits;
    }
    public int getDenies() {
        return this.denies;
    }
    
    public void setDenies(int denies) {
        this.denies = denies;
    }
    public int getGpm() {
        return this.gpm;
    }
    
    public void setGpm(int gpm) {
        this.gpm = gpm;
    }
    public int getXpm() {
        return this.xpm;
    }
    
    public void setXpm(int xpm) {
        this.xpm = xpm;
    }
    public int getOurogasto() {
        return this.ourogasto;
    }
    
    public void setOurogasto(int ourogasto) {
        this.ourogasto = ourogasto;
    }
    public int getDanoemtorre() {
        return this.danoemtorre;
    }
    
    public void setDanoemtorre(int danoemtorre) {
        this.danoemtorre = danoemtorre;
    }
    public int getHpcurado() {
        return this.hpcurado;
    }
    
    public void setHpcurado(int hpcurado) {
        this.hpcurado = hpcurado;
    }
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }
    public long getIdconta() {
        return this.idconta;
    }
    
    public void setIdconta(long idconta) {
        this.idconta = idconta;
    }
    public Set getHabilidadeses() {
        return this.habilidadeses;
    }
    
    public void setHabilidadeses(Set habilidadeses) {
        this.habilidadeses = habilidadeses;
    }




}


