package persistencia;
// Generated Jan 8, 2015 9:04:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private long idpartida;
     private int timevitorioso;
     private int duracao;
     private int torresradiant;
     private int torresdire;
     private int cluster;
     private int tempofb;
     private int tipolobby;
     private int idliga;
     private Set jogadoreses = new HashSet(0);

    public Partida() {
    }

	
    public Partida(long idpartida, int timevitorioso, int duracao, int torresradiant, int torresdire, int cluster, int tempofb, int tipolobby, int idliga) {
        this.idpartida = idpartida;
        this.timevitorioso = timevitorioso;
        this.duracao = duracao;
        this.torresradiant = torresradiant;
        this.torresdire = torresdire;
        this.cluster = cluster;
        this.tempofb = tempofb;
        this.tipolobby = tipolobby;
        this.idliga = idliga;
    }
    public Partida(long idpartida, int timevitorioso, int duracao, int torresradiant, int torresdire, int cluster, int tempofb, int tipolobby, int idliga, Set jogadoreses) {
       this.idpartida = idpartida;
       this.timevitorioso = timevitorioso;
       this.duracao = duracao;
       this.torresradiant = torresradiant;
       this.torresdire = torresdire;
       this.cluster = cluster;
       this.tempofb = tempofb;
       this.tipolobby = tipolobby;
       this.idliga = idliga;
       this.jogadoreses = jogadoreses;
    }
   
    public long getIdpartida() {
        return this.idpartida;
    }
    
    public void setIdpartida(long idpartida) {
        this.idpartida = idpartida;
    }
    public int getTimevitorioso() {
        return this.timevitorioso;
    }
    
    public void setTimevitorioso(int timevitorioso) {
        this.timevitorioso = timevitorioso;
    }
    public int getDuracao() {
        return this.duracao;
    }
    
    public void setDuracao(int duracao) {
        this.duracao = duracao;
    }
    public int getTorresradiant() {
        return this.torresradiant;
    }
    
    public void setTorresradiant(int torresradiant) {
        this.torresradiant = torresradiant;
    }
    public int getTorresdire() {
        return this.torresdire;
    }
    
    public void setTorresdire(int torresdire) {
        this.torresdire = torresdire;
    }
    public int getCluster() {
        return this.cluster;
    }
    
    public void setCluster(int cluster) {
        this.cluster = cluster;
    }
    public int getTempofb() {
        return this.tempofb;
    }
    
    public void setTempofb(int tempofb) {
        this.tempofb = tempofb;
    }
    public int getTipolobby() {
        return this.tipolobby;
    }
    
    public void setTipolobby(int tipolobby) {
        this.tipolobby = tipolobby;
    }
    public int getIdliga() {
        return this.idliga;
    }
    
    public void setIdliga(int idliga) {
        this.idliga = idliga;
    }
    public Set getJogadoreses() {
        return this.jogadoreses;
    }
    
    public void setJogadoreses(Set jogadoreses) {
        this.jogadoreses = jogadoreses;
    }




}


